apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: my-spring-app
        image: 519852036875.dkr.ecr.us-east-1.amazonaws.com/my-first-ecr:latest 
        imagePullPolicy: Always
        command: ["java","-jar","/myspringbootapp.jar"]
        ports:
        - containerPort: 8083
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
