apiVersion: v1
kind: Namespace
metadata:
   name: spring-app
   labels:
     app.kubernetes.io/name: springbootapp
---
kind: Pod
apiVersion: v1
metadata:
 name: spring-app
 namespace: spring-app
spec:
  containers:
    - name: my-spring-app
      image: 519852036875.dkr.ecr.us-east-1.amazonaws.com/my-first-ecr:latest
      imagePullPolicy: Always
      command: ["java","-jar","/myspringbootapp.jar"]
      ports:
      - containerPort: 8085
